# Generated by Django 5.1.1 on 2024-12-06 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='province',
            new_name='state',
        ),
    ]
